### ISSUE TITLE
Notifications in the stack disappear in random order

### ISSUE THREAD

**Issue by evgenoid** [reaviz/realayers#15]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Notifications in the stack disappear in random order

## Expected behavior
Notifications in the stack should disappear in order what they appear

https://user-images.githubusercontent.com/1290843/201059062-f777929a-bc24-4ccc-a394-393a8ddce73a.mov

**Comment by amcdnl** [comment]
I think its the hover killing the delay.

**Comment by evgenoid** [comment]
> I think its the hover killing the delay.

Actually no, setTimeout calls for every element in a stack on re-render.

**Comment by amcdnl** [comment]
If you hover the notification, it should reset the timer. Maybe the div is larger than you think that is resetting it?

**Comment by evgenoid** [comment]
> If you hover the notification, it should reset the timer. Maybe the div is larger than you think that is resetting it?

I know, but that's not the case. You can try on the storybook page.

**Comment by evgenoid** [comment]
Outdated
