### ISSUE TITLE
Dialog className prop should be passed to .inner div instead

### ISSUE THREAD

**Issue by steppy452** [reaviz/realayers#5]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Probably a bug? But, since the className prop is getting passed to the outer container which controls the alignment, placement, z-index etc things that probably won't be overridden. Instead, passing the prop to the .inner div makes more sense so users can affect padding, borders, colors, etc.

## Expected behavior

I am able to change [border-radius] of the dialog. background.

## Minimal reproduction of the problem with instructions
```
.dialog {
  border-radius: 25px;
}

<Dialog className={css.dialog} {...otherProps} />
```

* Pass a className to Dialog component with the class changing something like border-radius
* See that the dialog doesn't change

## What is the motivation / use case for changing the behavior?

Customizability

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- realayers version: 2.5.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amcdnl** [comment]
done!
